# Generated by Django 5.2.8 on 2025-11-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0002_admin_lookup_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="end_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the end point (Zone 38N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="end_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the end point (Zone 38N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="start_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the start point (Zone 38N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="start_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the start point (Zone 38N)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
