# Generated by Django 5.2.8 on 2025-11-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0003_road_end_easting_road_end_northing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadsection",
            name="attachments",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="end_coordinates",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="geometry",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="gravel_thickness_cm",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="inspection_date",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="inspector_name",
        ),
        migrations.RemoveField(
            model_name="roadsection",
            name="start_coordinates",
        ),
        migrations.AddField(
            model_name="roadsection",
            name="sequence_on_road",
            field=models.PositiveIntegerField(
                default=1, help_text="Ordered position of this section along the parent road"
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="name",
            field=models.CharField(
                blank=True, help_text="Optional section name or landmark", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="surface_thickness_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wearing course or gravel thickness (cm) for gravel/paved surfaces",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="admin_zone_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override when the section crosses into a different zone",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="section_overrides",
                to="grms.adminzone",
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="admin_woreda_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override when the section crosses into a different woreda",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="section_overrides",
                to="grms.adminworeda",
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="notes",
            field=models.TextField(blank=True, help_text="Inventory notes for this section"),
        ),
        migrations.AlterField(
            model_name="roadsection",
            name="length_km",
            field=models.DecimalField(
                decimal_places=3,
                editable=False,
                help_text="Section length (km) computed from chainage",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="roadsection",
            name="surface_type",
            field=models.CharField(
                choices=[
                    ("Earth", "Earth"),
                    ("Gravel", "Gravel"),
                    ("DBST", "DBST"),
                    ("Asphalt", "Asphalt"),
                    ("Sealed", "Sealed"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterModelOptions(
            name="roadsection",
            options={
                "ordering": ("road", "sequence_on_road", "section_number"),
                "verbose_name": "Road section",
                "verbose_name_plural": "Road sections",
            },
        ),
        migrations.AlterUniqueTogether(
            name="roadsection",
            unique_together={("road", "section_number"), ("road", "sequence_on_road")},
        ),
    ]
