# Generated by Django 5.2.8 on 2025-11-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0004_alter_activitylookup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylookup",
            options={
                "ordering": ["activity_code"],
                "verbose_name": "Activity lookup",
                "verbose_name_plural": "Activity lookups",
            },
        ),
        migrations.AlterModelOptions(
            name="adminworeda",
            options={
                "ordering": ["zone__name", "name"],
                "verbose_name": "Administrative woreda",
                "verbose_name_plural": "Administrative woredas",
            },
        ),
        migrations.AlterModelOptions(
            name="adminzone",
            options={
                "ordering": ["name"],
                "verbose_name": "Administrative zone",
                "verbose_name_plural": "Administrative zones",
            },
        ),
        migrations.AlterModelOptions(
            name="annualworkplan",
            options={
                "verbose_name": "Annual work plan",
                "verbose_name_plural": "Annual work plans",
            },
        ),
        migrations.AlterModelOptions(
            name="benefitfactor",
            options={
                "verbose_name": "Benefit factor",
                "verbose_name_plural": "Benefit factors",
            },
        ),
        migrations.AlterModelOptions(
            name="bridgeconditionsurvey",
            options={
                "verbose_name": "Bridge condition survey",
                "verbose_name_plural": "Bridge condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="bridgedetail",
            options={
                "verbose_name": "Bridge detail",
                "verbose_name_plural": "Bridge details",
            },
        ),
        migrations.AlterModelOptions(
            name="conditionfactor",
            options={
                "verbose_name": "Condition factor",
                "verbose_name_plural": "Condition factors",
            },
        ),
        migrations.AlterModelOptions(
            name="conditionrating",
            options={
                "verbose_name": "Condition rating",
                "verbose_name_plural": "Condition ratings",
            },
        ),
        migrations.AlterModelOptions(
            name="culvertconditionsurvey",
            options={
                "verbose_name": "Culvert condition survey",
                "verbose_name_plural": "Culvert condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="culvertdetail",
            options={
                "verbose_name": "Culvert detail",
                "verbose_name_plural": "Culvert details",
            },
        ),
        migrations.AlterModelOptions(
            name="distressactivity",
            options={
                "verbose_name": "Distress activity",
                "verbose_name_plural": "Distress activities",
            },
        ),
        migrations.AlterModelOptions(
            name="distresscondition",
            options={
                "ordering": ["distress__distress_code", "severity_code", "extent_code"],
                "verbose_name": "Distress condition",
                "verbose_name_plural": "Distress conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="distresstype",
            options={
                "ordering": ["distress_code"],
                "verbose_name": "Distress type",
                "verbose_name_plural": "Distress types",
            },
        ),
        migrations.AlterModelOptions(
            name="forddetail",
            options={
                "verbose_name": "Ford detail",
                "verbose_name_plural": "Ford details",
            },
        ),
        migrations.AlterModelOptions(
            name="furnitureconditiondetailedsurvey",
            options={
                "ordering": ["-inspection_date", "furniture_id"],
                "verbose_name": "Furniture condition detailed survey",
                "verbose_name_plural": "Furniture condition detailed surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="furnitureconditionsurvey",
            options={
                "verbose_name": "Furniture condition survey",
                "verbose_name_plural": "Furniture condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="furnitureinventory",
            options={
                "verbose_name": "Furniture inventory",
                "verbose_name_plural": "Furniture inventories",
            },
        ),
        migrations.AlterModelOptions(
            name="gabionwalldetail",
            options={
                "verbose_name": "Gabion wall detail",
                "verbose_name_plural": "Gabion wall details",
            },
        ),
        migrations.AlterModelOptions(
            name="interventionlookup",
            options={
                "verbose_name": "Intervention lookup",
                "verbose_name_plural": "Intervention lookups",
            },
        ),
        migrations.AlterModelOptions(
            name="nightadjustmentlookup",
            options={
                "verbose_name": "Night adjustment lookup",
                "verbose_name_plural": "Night adjustment lookups",
            },
        ),
        migrations.AlterModelOptions(
            name="otherstructureconditionsurvey",
            options={
                "verbose_name": "Other structure condition survey",
                "verbose_name_plural": "Other structure condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="pculookup",
            options={
                "verbose_name": "PCU lookup",
                "verbose_name_plural": "PCU lookups",
            },
        ),
        migrations.AlterModelOptions(
            name="prioritizationresult",
            options={
                "ordering": ["fiscal_year", "priority_rank"],
                "verbose_name": "Prioritization result",
                "verbose_name_plural": "Prioritization results",
            },
        ),
        migrations.AlterModelOptions(
            name="qastatus",
            options={"verbose_name": "QA status", "verbose_name_plural": "QA statuses"},
        ),
        migrations.AlterModelOptions(
            name="retainingwalldetail",
            options={
                "verbose_name": "Retaining wall detail",
                "verbose_name_plural": "Retaining wall details",
            },
        ),
        migrations.AlterModelOptions(
            name="road",
            options={"verbose_name": "Road", "verbose_name_plural": "Roads"},
        ),
        migrations.AlterModelOptions(
            name="roadconditiondetailedsurvey",
            options={
                "ordering": ["-inspection_date", "road_segment_id"],
                "verbose_name": "Road condition detailed survey",
                "verbose_name_plural": "Road condition detailed surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="roadconditionsurvey",
            options={
                "verbose_name": "Road condition survey",
                "verbose_name_plural": "Road condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="roadsectionintervention",
            options={
                "verbose_name": "Road section intervention",
                "verbose_name_plural": "Road section interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="roadsegment",
            options={
                "verbose_name": "Road segment",
                "verbose_name_plural": "Road segments",
            },
        ),
        migrations.AlterModelOptions(
            name="structureconditiondetailedsurvey",
            options={
                "ordering": ["-inspection_date", "structure_id"],
                "verbose_name": "Structure condition detailed survey",
                "verbose_name_plural": "Structure condition detailed surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="structureconditionsurvey",
            options={
                "verbose_name": "Structure condition survey",
                "verbose_name_plural": "Structure condition surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="structureintervention",
            options={
                "verbose_name": "Structure intervention",
                "verbose_name_plural": "Structure interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="structureinventory",
            options={
                "verbose_name": "Structure inventory",
                "verbose_name_plural": "Structure inventories",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficcountrecord",
            options={
                "verbose_name": "Traffic count record",
                "verbose_name_plural": "Traffic count records",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficcyclesummary",
            options={
                "verbose_name": "Traffic cycle summary",
                "verbose_name_plural": "Traffic cycle summaries",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficforprioritization",
            options={
                "verbose_name": "Traffic for prioritization record",
                "verbose_name_plural": "Traffic for prioritization records",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficqc",
            options={
                "verbose_name": "Traffic quality check",
                "verbose_name_plural": "Traffic quality checks",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficsurvey",
            options={
                "verbose_name": "Traffic survey",
                "verbose_name_plural": "Traffic surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="trafficsurveysummary",
            options={
                "verbose_name": "Traffic survey summary",
                "verbose_name_plural": "Traffic survey summaries",
            },
        ),
        migrations.AlterModelOptions(
            name="unitcost",
            options={"verbose_name": "Unit cost", "verbose_name_plural": "Unit costs"},
        ),
        migrations.AlterField(
            model_name="road",
            name="end_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the end point (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="end_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the end point (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="start_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the start point (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="start_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the start point (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roadsection",
            name="section_number",
            field=models.PositiveIntegerField(
                help_text="Section identifier within the road"
            ),
        ),
    ]
