# Generated by Django 5.2.8 on 2025-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0005_alter_activitylookup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="last_mci_update",
            field=models.DateField(
                blank=True, help_text="Most recent MCI update date", null=True
            ),
        ),
    ]
