# Generated by Django 5.2.8 on 2025-11-21 11:40

import grms.gis_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0006_road_last_mci_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadsection",
            name="end_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the section end (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="end_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the section end (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="section_end_coordinates",
            field=grms.gis_fields.DjangoPointField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="section_start_coordinates",
            field=grms.gis_fields.DjangoPointField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="start_easting",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM easting for the section start (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="start_northing",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="UTM northing for the section start (Zone 37N)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
