# Generated by Django 5.2.8 on 2025-11-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0007_roadsection_end_easting_roadsection_end_northing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherstructureconditionsurvey",
            name="wall_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="headwall_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="deck_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="inlet_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="outlet_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="pier_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="abutment_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="wearing_surface",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="barrel_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.AlterField(
            model_name="otherstructureconditionsurvey",
            name="ford_condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="grms.conditionrating",
            ),
        ),
        migrations.DeleteModel(
            name="ConditionFactor",
        ),
    ]
