# Generated by Django 5.2.8 on 2025-11-25 11:44

import grms.gis_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0008_alter_otherstructureconditionsurvey_wall_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="geometry",
            field=grms.gis_fields.DjangoLineStringField(
                blank=True, help_text="Road geometry (LineString)", null=True
            ),
        ),
        migrations.AddField(
            model_name="roadsection",
            name="geometry",
            field=grms.gis_fields.DjangoLineStringField(
                blank=True, help_text="Section geometry (LineString)", null=True
            ),
        ),
    ]
