# Generated by ChatGPT on 2025-02-13

from django.contrib.gis.db.models.fields import LineStringField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0009_road_geometry_roadsection_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="geometry",
            field=LineStringField(
                blank=True, geography=True, help_text="Road geometry (LineString)", null=True
            ),
        ),
    ]
