# Generated by ChatGPT on 2025-02-13

from django.db import migrations
import grms.gis_fields


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0009_road_geometry_roadsection_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="geometry",
            field=grms.gis_fields.DjangoLineStringField(
                blank=True, geography=True, help_text="Road geometry (LineString)", null=True
            ),
        ),
    ]
