# Generated by Django 5.2.8 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0015_update_furniture_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culvertdetail",
            name="span_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Span (slab/box culverts)",
                max_digits=6,
                null=True,
            ),
        ),
    ]
