# Generated by Django 5.2.8 on 2025-11-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0015_structureinventory_section_required"),
        ("grms", "0016_alter_culvertdetail_span_m"),
    ]

    operations = []
