# Generated by Django 5.2.8 on 2025-11-27 11:34

import grms.gis_fields._load_spatial_fields.<locals>
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0017_merge_20251127_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureinventory',
            options={'ordering': ['road', 'structure_category', 'station_km', 'start_chainage_km'], 'verbose_name': 'Structure inventory', 'verbose_name_plural': 'Structure inventories'},
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='end_chainage_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='End chainage (km) for line structures', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='geometry_type',
            field=models.CharField(choices=[('Point', 'Point'), ('Line', 'Line')], default='Point', help_text='Indicates whether the structure is mapped as a point or line', max_length=10),
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional latitude override for point structures', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='location_line',
            field=grms.gis_fields._load_spatial_fields.<locals>.DjangoLineStringField(blank=True, help_text='Geometry of line structures', null=True),
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional longitude override for point structures', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='structureinventory',
            name='start_chainage_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Start chainage (km) for line structures', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='structureinventory',
            name='station_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Location along road (chainage km)', max_digits=8, null=True),
        ),
    ]
