# Generated by Django 5.2.8 on 2025-11-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0017_merge_20251127_1354'),
        ('grms', '0018_alter_structureinventory_options_and_more'),
    ]

    operations = [
    ]
