# Generated by Django 5.2.8 on 2025-11-27 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0019_merge_20251127_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structureinventory",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Road section containing the structure",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="structures",
                to="grms.roadsection",
            ),
        ),
    ]
