# Generated by Django 5.2.8 on 2025-11-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0020_alter_structureinventory_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficsurvey",
            name="road_segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_traffic_surveys",
                to="grms.roadsegment",
            ),
        ),
    ]
