# Generated by Django 5.2.8 on 2025-11-28 08:42

from django.core.validators import RegexValidator
from django.db import migrations, models


def populate_road_identifier(apps, schema_editor):
    Road = apps.get_model("grms", "Road")
    for road in Road.objects.all():
        if road.road_identifier:
            continue
        road.road_identifier = f"RTR-{road.pk}"
        road.save(update_fields=["road_identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0021_alter_trafficsurvey_road_segment"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="road_identifier",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier such as RTR-1",
                max_length=20,
                null=True,
                unique=True,
                validators=[RegexValidator(r"^RTR-\d+$", "Road ID must match RTR-<number> format.")],
                verbose_name="Road ID",
            ),
        ),
        migrations.RunPython(populate_road_identifier, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="road",
            name="road_identifier",
            field=models.CharField(
                help_text="Unique identifier such as RTR-1",
                max_length=20,
                unique=True,
                validators=[RegexValidator(r"^RTR-\d+$", "Road ID must match RTR-<number> format.")],
                verbose_name="Road ID",
            ),
        ),
    ]
