# Generated by Django 5.2.8 on 2025-12-02 07:40

import django.db.models.deletion
from django.db import migrations, models


def copy_benefitfactor_inputs_to_socioeconomic(apps, schema_editor):
    BenefitFactor = apps.get_model("grms", "BenefitFactor")
    RoadSocioEconomic = apps.get_model("grms", "RoadSocioEconomic")

    for benefit in BenefitFactor.objects.all():
        RoadSocioEconomic.objects.update_or_create(
            road_id=benefit.road_id,
            fiscal_year=getattr(benefit, "fiscal_year", 0),
            defaults={
                "trading_centers_count": getattr(
                    benefit, "trading_centers_count", None
                ),
                "villages_connected_count": getattr(
                    benefit, "villages_connected_count", None
                ),
                "adt_value": getattr(benefit, "traffic_vehicles_per_day", None),
                "farmland_percentage": getattr(benefit, "farmland_percentage", None),
                "health_centers_count": getattr(benefit, "health_centers_count", None),
                "educational_institutions_count": getattr(
                    benefit, "educational_institutions_count", None
                ),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0022_add_road_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall category weight",
                        max_digits=6,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Benefit category",
                "verbose_name_plural": "Benefit categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoadLinkTypeLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code such as TRUNK or LINK",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priority_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight used when computing BF1 scores",
                        max_digits=6,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Road link type",
                "verbose_name_plural": "Road link types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="benefitfactor",
            options={
                "ordering": ["-fiscal_year", "road__road_identifier"],
                "verbose_name": "Benefit factor",
                "verbose_name_plural": "Benefit factors",
            },
        ),
        migrations.AddField(
            model_name="benefitfactor",
            name="bf1_transport_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="benefitfactor",
            name="bf2_agriculture_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="benefitfactor",
            name="bf3_social_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="benefitfactor",
            name="calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benefitfactor",
            name="fiscal_year",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="benefitfactor",
            unique_together={("road", "fiscal_year")},
        ),
        migrations.AlterField(
            model_name="benefitfactor",
            name="total_benefit_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="prioritizationresult",
            name="benefit_score",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="prioritizationresult",
            name="ranking_index",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.CreateModel(
            name="BenefitCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "indicator_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Weight within the category",
                        max_digits=6,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="grms.benefitcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefit criterion",
                "verbose_name_plural": "Benefit criteria",
                "ordering": ["category__code", "code"],
            },
        ),
        migrations.AddField(
            model_name="road",
            name="link_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Functional road class used for connectivity/prioritization (Trunk, Link, Main access, Collector, Feeder).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roads",
                to="grms.roadlinktypelookup",
            ),
        ),
        migrations.CreateModel(
            name="BenefitCriterionScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "exact_match_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("score", models.DecimalField(decimal_places=3, max_digits=8)),
                ("notes", models.TextField(blank=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scales",
                        to="grms.benefitcriterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefit criterion scale",
                "verbose_name_plural": "Benefit criterion scales",
                "indexes": [
                    models.Index(
                        fields=[
                            "criterion",
                            "min_value",
                            "max_value",
                            "exact_match_code",
                        ],
                        name="grms_benefi_criteri_deaaa3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoadSocioEconomic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "trading_centers_count",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "villages_connected_count",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "adt_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "farmland_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("cooperative_centers_count", models.IntegerField(default=1)),
                ("markets_connected_count", models.IntegerField(default=1)),
                ("health_centers_count", models.IntegerField(default=1)),
                ("educational_institutions_count", models.IntegerField(default=1)),
                ("development_projects_count", models.IntegerField(default=1)),
                (
                    "population_served_override",
                    models.IntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="socioeconomic_overrides",
                        to="grms.roadlinktypelookup",
                    ),
                ),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socioeconomic_inputs",
                        to="grms.road",
                    ),
                ),
            ],
            options={
                "verbose_name": "Road socio-economic input",
                "verbose_name_plural": "Road socio-economic inputs",
                "ordering": ["-fiscal_year", "road__road_identifier"],
                "unique_together": {("road", "fiscal_year")},
            },
        ),
        migrations.RunPython(
            code=copy_benefitfactor_inputs_to_socioeconomic,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="educational_institutions_count",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="farmland_percentage",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="health_centers_count",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="last_calculated",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="trading_centers_count",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="traffic_vehicles_per_day",
        ),
        migrations.RemoveField(
            model_name="benefitfactor",
            name="villages_connected_count",
        ),
    ]
