# Generated by Django 5.2.8 on 2025-12-02 08:14

import django.db.models.deletion
from django.db import migrations, models


def copy_link_type_scores(apps, schema_editor):
    Lookup = apps.get_model("grms", "RoadLinkTypeLookup")
    for row in Lookup.objects.all():
        # priority_weight exists before removal operations execute
        if hasattr(row, "priority_weight"):
            row.score = row.priority_weight
            row.save(update_fields=["score"])


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0024_seed_road_link_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadsocioeconomic",
            options={
                "ordering": ["road__road_identifier"],
                "verbose_name": "Road socio-economic input",
                "verbose_name_plural": "Road socio-economic inputs",
            },
        ),
        migrations.RemoveIndex(
            model_name="benefitcriterionscale",
            name="grms_benefi_criteri_deaaa3_idx",
        ),
        migrations.RenameField(
            model_name="benefitcriterion",
            old_name="indicator_weight",
            new_name="weight",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="adt_value",
            new_name="adt_override",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="cooperative_centers_count",
            new_name="cooperative_centers",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="development_projects_count",
            new_name="development_projects",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="educational_institutions_count",
            new_name="education_centers",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="health_centers_count",
            new_name="health_centers",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="markets_connected_count",
            new_name="markets_connected",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="trading_centers_count",
            new_name="trading_centers",
        ),
        migrations.RenameField(
            model_name="roadsocioeconomic",
            old_name="villages_connected_count",
            new_name="villages_connected",
        ),
        migrations.AlterUniqueTogether(
            name="roadsocioeconomic",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="roadlinktypelookup",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Lookup-driven score for prioritisation",
                max_digits=6,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=copy_link_type_scores,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="benefitcriterionscale",
            name="exact_match_code",
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="description",
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="priority_weight",
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="road_link_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="socioeconomic_records",
                to="grms.roadlinktypelookup",
            ),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="road",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socioeconomic",
                to="grms.road",
            ),
        ),
        migrations.AddIndex(
            model_name="benefitcriterionscale",
            index=models.Index(
                fields=["criterion", "min_value", "max_value"],
                name="grms_benefi_criteri_35bacf_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="fiscal_year",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="link_type_override",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="population_served_override",
        ),
    ]
