# Generated by Django 5.2.8 on 2025-12-02 08:36

from django.db import migrations, models


def copy_population_to_socioeconomic(apps, schema_editor):
    Road = apps.get_model("grms", "Road")
    RoadSocioEconomic = apps.get_model("grms", "RoadSocioEconomic")

    for road in Road.objects.exclude(population_served__isnull=True):
        socio, created = RoadSocioEconomic.objects.get_or_create(
            road_id=road.id,
            defaults={"population_served": road.population_served},
        )
        if not created and socio.population_served is None:
            socio.population_served = road.population_served
            socio.save(update_fields=["population_served"])


def copy_population_to_road(apps, schema_editor):
    Road = apps.get_model("grms", "Road")
    RoadSocioEconomic = apps.get_model("grms", "RoadSocioEconomic")

    for socio in RoadSocioEconomic.objects.exclude(population_served__isnull=True):
        Road.objects.filter(pk=socio.road_id).update(
            population_served=socio.population_served
        )


def drop_population_column(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        return

    schema_editor.execute("ALTER TABLE grms_road DROP COLUMN IF EXISTS population_served;")


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0025_alter_roadsocioeconomic_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="population_served",
            field=models.IntegerField(
                blank=True, help_text="Population served by this road", null=True
            ),
        ),
        migrations.RunPython(copy_population_to_socioeconomic, copy_population_to_road),
        migrations.SeparateDatabaseAndState(
            # The column may already be missing on some databases; drop it only if present
            database_operations=[
                migrations.RunPython(drop_population_column, migrations.RunPython.noop)
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="road",
                    name="population_served",
                ),
            ],
        ),
    ]
