# Generated by Django 5.2.8 on 2025-12-02 09:51

from decimal import Decimal

from django.db import migrations, models


def migrate_socio_fields(apps, schema_editor):
    Road = apps.get_model("grms", "Road")
    Socio = apps.get_model("grms", "RoadSocioEconomic")

    for road in Road.objects.all():
        socio, _ = Socio.objects.get_or_create(
            road_id=road.id,
            defaults={"road_link_type_id": getattr(road, "link_type_id", None)},
        )
        if getattr(road, "population_served", None) is not None:
            socio.population_served = road.population_served
        if hasattr(socio, "farmland_percentage") and socio.farmland_percentage is not None:
            socio.farmland_percent = socio.farmland_percentage
        if hasattr(socio, "markets_connected") and socio.markets_connected is not None:
            socio.markets = socio.markets_connected
        if hasattr(socio, "villages_connected") and socio.villages_connected is not None:
            socio.villages = socio.villages_connected
        socio.save()


def ensure_population_defaults(apps, schema_editor):
    Socio = apps.get_model("grms", "RoadSocioEconomic")
    Socio.objects.filter(population_served__isnull=True).update(population_served=0)


def noop_reverse(apps, schema_editor):
    # Data rollback not required
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0026_seed_benefit_scoring"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Benefit category",
                "verbose_name_plural": "Benefit categories",
            },
        ),
        migrations.AlterModelOptions(
            name="benefitcriterion",
            options={
                "ordering": ["category__name", "name"],
                "verbose_name": "Benefit criterion",
                "verbose_name_plural": "Benefit criteria",
            },
        ),
        migrations.AddField(
            model_name="benefitcategory",
            name="weight_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="benefitcriterion",
            name="weight_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="farmland_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="markets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="villages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(ensure_population_defaults, noop_reverse),
        migrations.RunPython(migrate_socio_fields, noop_reverse),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="population_served",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="code",
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="weight",
        ),
        migrations.AlterUniqueTogether(
            name="benefitcriterion",
            unique_together={("category", "name")},
        ),
        migrations.RemoveField(
            model_name="benefitcriterionscale",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="road",
            name="population_served",
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="farmland_percentage",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="markets_connected",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="villages_connected",
        ),
        migrations.AlterField(
            model_name="benefitcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="max_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="min_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="roadlinktypelookup",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="roadlinktypelookup",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="adt_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="cooperative_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="development_projects",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="education_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="health_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="trading_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="code",
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="weight",
        ),
    ]
