# Generated by Django 5.2.8 on 2025-12-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0026_remove_road_population_served_and_more'),
        ('grms', '0026_seed_benefit_scoring'),
    ]

    operations = [
    ]
