# Generated by Django 5.2.8 on 2025-12-02 09:51

from decimal import Decimal

from django.db import migrations, models


def normalize_link_type_codes(apps, schema_editor):
    """Shrink existing road link type codes so they fit within 5 characters.

    Historic data used longer textual codes (e.g., full names) which would
    violate the new ``max_length=5`` constraint. We normalise them here to
    ensure the subsequent ``AlterField`` succeeds without raising
    ``DataError``.
    """

    Lookup = apps.get_model("grms", "RoadLinkTypeLookup")

    used_codes = set()
    for link_type in Lookup.objects.all().order_by("id"):
        raw_code = (link_type.code or "").strip()

        # Start from the provided code (if any) or a fallback derived from the
        # primary key, then truncate to five characters.
        base = raw_code or f"LT{link_type.pk}"
        candidate = base[:5] or f"LT{link_type.pk}"[:5]

        # Resolve collisions by appending a numeric suffix while respecting
        # the five-character limit.
        suffix = 1
        while candidate in used_codes:
            trimmed_base = candidate[:4] if len(candidate) >= 4 else (candidate + "X" * (4 - len(candidate)))
            candidate = f"{trimmed_base}{suffix}"[:5]
            suffix += 1

        if link_type.code != candidate:
            link_type.code = candidate
            link_type.save(update_fields=["code"])

        used_codes.add(candidate)


def migrate_socio_fields(apps, schema_editor):
    Road = apps.get_model("grms", "Road")
    Socio = apps.get_model("grms", "RoadSocioEconomic")

    for road in Road.objects.all():
        socio, _ = Socio.objects.get_or_create(
            road_id=road.id,
            defaults={"road_link_type_id": getattr(road, "link_type_id", None)},
        )
        if getattr(road, "population_served", None) is not None:
            socio.population_served = road.population_served
        if hasattr(socio, "farmland_percentage") and socio.farmland_percentage is not None:
            socio.farmland_percent = socio.farmland_percentage
        if hasattr(socio, "markets_connected") and socio.markets_connected is not None:
            socio.markets = socio.markets_connected
        if hasattr(socio, "villages_connected") and socio.villages_connected is not None:
            socio.villages = socio.villages_connected
        socio.save()


def ensure_population_defaults(apps, schema_editor):
    Socio = apps.get_model("grms", "RoadSocioEconomic")
    fields = {field.name for field in Socio._meta.get_fields()}
    if "population_served" not in fields:
        return

    Socio.objects.filter(population_served__isnull=True).update(population_served=0)


def noop_reverse(apps, schema_editor):
    # Data rollback not required
    pass


def drop_road_population_column(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        return

    schema_editor.execute("ALTER TABLE grms_road DROP COLUMN IF EXISTS population_served;")


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0027_merge_20251202_1150"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Benefit category",
                "verbose_name_plural": "Benefit categories",
            },
        ),
        migrations.AlterModelOptions(
            name="benefitcriterion",
            options={
                "ordering": ["category__name", "name"],
                "verbose_name": "Benefit criterion",
                "verbose_name_plural": "Benefit criteria",
            },
        ),
        migrations.AddField(
            model_name="benefitcategory",
            name="weight_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="benefitcriterion",
            name="weight_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="farmland_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="markets",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roadsocioeconomic",
            name="villages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(ensure_population_defaults, noop_reverse),
        migrations.RunPython(migrate_socio_fields, noop_reverse),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="population_served",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="code",
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="benefitcategory",
            name="weight",
        ),
        migrations.AlterUniqueTogether(
            name="benefitcriterion",
            unique_together={("category", "name")},
        ),
        migrations.RemoveField(
            model_name="benefitcriterionscale",
            name="notes",
        ),
        migrations.SeparateDatabaseAndState(
            # The column may already be absent on some databases; drop it only if present
            database_operations=[
                migrations.RunPython(drop_road_population_column, noop_reverse)
            ],
            state_operations=[],
        ),
        migrations.RemoveField(
            model_name="roadlinktypelookup",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="farmland_percentage",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="markets_connected",
        ),
        migrations.RemoveField(
            model_name="roadsocioeconomic",
            name="villages_connected",
        ),
        migrations.RunPython(normalize_link_type_codes, noop_reverse),
        migrations.AlterField(
            model_name="benefitcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="max_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="min_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="roadlinktypelookup",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="roadlinktypelookup",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="adt_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="cooperative_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="development_projects",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="education_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="health_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadsocioeconomic",
            name="trading_centers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="code",
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="description",
        ),
        migrations.RemoveField(
            model_name="benefitcriterion",
            name="weight",
        ),
    ]
