# Generated by Django 5.2.8 on 2025-12-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0027_merge_20251202_1150'),
        ('grms', '0028_seed_benefit_and_link_types'),
    ]

    operations = [
    ]
