# Generated by Django 5.2.8 on 2025-12-02 11:40

from django.db import migrations, models


def drop_population_served(apps, schema_editor):
    table = 'grms_road'
    column = 'population_served'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name=%s AND column_name=%s",
            [table, column],
        )
        exists = cursor.fetchone()
        if exists:
            schema_editor.execute(f"ALTER TABLE {table} DROP COLUMN {column}")


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0029_prioritization_lookup_overhaul"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefitcriterion",
            options={
                "ordering": ["category__code", "code"],
                "verbose_name": "Benefit criterion",
                "verbose_name_plural": "Benefit criteria",
            },
        ),
        migrations.RunPython(drop_population_served, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="benefitcriterionscale",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
