# Generated by Django 5.2.8 on 2025-12-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0029_merge_20251202_1257'),
        ('grms', '0030_alter_benefitcriterion_options_and_more'),
    ]

    operations = [
    ]
