# Generated by Django 5.2.8 on 2025-12-04 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0031_merge_20251202_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadsocioeconomic',
            options={'ordering': ['road__road_identifier'], 'verbose_name': 'Road socio-economic input', 'verbose_name_plural': 'Road socio-economic'},
        ),
        migrations.AlterField(
            model_name='road',
            name='admin_woreda',
            field=models.ForeignKey(help_text='Administrative Woreda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roads', to='grms.adminworeda'),
        ),
        migrations.AlterField(
            model_name='road',
            name='link_type',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, help_text='Functional road class used for connectivity/prioritization (Trunk, Link, Main access, Collector, Feeder).', on_delete=django.db.models.deletion.PROTECT, related_name='roads', to='grms.roadlinktypelookup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadsocioeconomic',
            name='population_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
