# Generated by Django 5.2.8 on 2025-12-04 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0031_merge_20251202_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadsocioeconomic',
            options={'ordering': ['road__road_identifier'], 'verbose_name': 'Road socio-economic input', 'verbose_name_plural': 'Road socio-economic'},
        ),
        migrations.AlterField(
            model_name='road',
            name='admin_woreda',
            field=models.ForeignKey(help_text='Administrative Woreda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roads', to='grms.adminworeda'),
        ),
        migrations.AlterField(
            model_name='road',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, help_text='Functional road class used for connectivity/prioritization (Trunk, Link, Main access, Collector, Feeder).', on_delete=django.db.models.deletion.PROTECT, related_name='roads', to='grms.roadlinktypelookup'),
        ),
        migrations.RunSQL(
            "ALTER TABLE grms_roadsocioeconomic DROP CONSTRAINT IF EXISTS grms_roadsocioeconomic_population_served_65d455e0_check;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="-- no-op: population_served constraint already exists",
            reverse_sql="-- no-op",
        ),
    ]
