# Generated by Django 5.2.8 on 2025-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0032_alter_roadsocioeconomic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsocioeconomic',
            name='population_served',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
