# Generated by Django 5.2.8 on 2025-12-10 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0033_alter_roadsocioeconomic_population_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCIWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('weight_drainage', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('weight_shoulder', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4)),
                ('weight_surface', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='benefitcategory',
            options={'ordering': ['code'], 'verbose_name': 'Benefit category', 'verbose_name_plural': 'Benefit categories'},
        ),
        migrations.AlterModelOptions(
            name='benefitcriterion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='benefitcriterionscale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roadconditionsurvey',
            options={'verbose_name': 'Road condition survey', 'verbose_name_plural': 'Road condition survey'},
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='calculated_mci',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='drainage_condition_left',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='drainage_condition_right',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='intervention_recommended',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='shoulder_condition_left',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='shoulder_condition_right',
        ),
        migrations.RemoveField(
            model_name='roadconditionsurvey',
            name='surface_condition_factor',
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='ditch_left_present',
            field=models.BooleanField(default=False, help_text='Indicates if left-side drainage/ditch exists.'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='ditch_right_present',
            field=models.BooleanField(default=False, help_text='Indicates if right-side drainage/ditch exists.'),
        ),
        migrations.CreateModel(
            name='ConditionFactorLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('drainage', 'Drainage Condition'), ('shoulder', 'Shoulder Condition'), ('surface', 'Surface Condition')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('factor_value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['factor_type', 'rating'],
                'unique_together': {('factor_type', 'rating')},
            },
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='drainage_left',
            field=models.ForeignKey(blank=True, limit_choices_to={'factor_type': 'drainage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drainage_left_surveys', to='grms.conditionfactorlookup'),
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='drainage_right',
            field=models.ForeignKey(blank=True, limit_choices_to={'factor_type': 'drainage'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drainage_right_surveys', to='grms.conditionfactorlookup'),
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='shoulder_left',
            field=models.ForeignKey(blank=True, limit_choices_to={'factor_type': 'shoulder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoulder_left_surveys', to='grms.conditionfactorlookup'),
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='shoulder_right',
            field=models.ForeignKey(blank=True, limit_choices_to={'factor_type': 'shoulder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoulder_right_surveys', to='grms.conditionfactorlookup'),
        ),
        migrations.AddField(
            model_name='roadconditionsurvey',
            name='surface_condition',
            field=models.ForeignKey(blank=True, limit_choices_to={'factor_type': 'surface'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surface_surveys', to='grms.conditionfactorlookup'),
        ),
        migrations.CreateModel(
            name='SegmentMCIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('drainage_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('shoulder_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('surface_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mci_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mci_results', to='grms.roadsegment')),
                ('survey', models.OneToOneField(help_text='The condition survey from which this MCI is derived', on_delete=django.db.models.deletion.CASCADE, related_name='mci_result', to='grms.roadconditionsurvey')),
                ('weight_config', models.ForeignKey(help_text='Weight configuration used at time of computation', on_delete=django.db.models.deletion.PROTECT, to='grms.mciweightconfig')),
            ],
            options={
                'verbose_name': 'Segment MCI result',
                'verbose_name_plural': 'Segment MCI results',
                'ordering': ['-survey_date', 'road_segment'],
            },
        ),
    ]
