# Generated by Django 5.2.9 on 2025-12-11 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0034_mciweightconfig_alter_benefitcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="deck_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="barrel_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="structureconditionsurvey",
            name="condition_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Overall condition (Good/Fair/Poor/Bad)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="otherstructureconditionsurvey",
            name="ford_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="abutment_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="wearing_surface",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherstructureconditionsurvey",
            name="wall_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="outlet_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bridgeconditionsurvey",
            name="pier_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="inlet_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="culvertconditionsurvey",
            name="headwall_condition",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="furnitureconditionsurvey",
            name="condition_rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="conditionfactorlookup",
            options={
                "ordering": ["factor_type", "rating"],
                "verbose_name": "Condition factor",
                "verbose_name_plural": "Condition factors",
            },
        ),
        migrations.AlterModelOptions(
            name="roadconditionsurvey",
            options={"ordering": ["-inspection_date", "road_segment"]},
        ),
        migrations.AlterModelOptions(
            name="segmentmciresult",
            options={"ordering": ["-survey_date", "road_segment"]},
        ),
        migrations.RemoveField(
            model_name="roadsectionintervention",
            name="calculated_mci",
        ),
        migrations.AddField(
            model_name="roadconditionsurvey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadconditionsurvey",
            name="gravel_thickness_mm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="roadconditionsurvey",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="segmentmciresult",
            name="recommended_intervention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mci_results",
                to="grms.interventionlookup",
            ),
        ),
        migrations.AlterField(
            model_name="conditionfactorlookup",
            name="factor_type",
            field=models.CharField(
                choices=[
                    ("drainage", "Drainage condition"),
                    ("shoulder", "Shoulder condition"),
                    ("surface", "Surface condition"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roadconditionsurvey",
            name="is_there_bottleneck",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="segmentmciresult",
            name="survey",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mci_result",
                to="grms.roadconditionsurvey",
            ),
        ),
        migrations.AlterField(
            model_name="segmentmciresult",
            name="weight_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="grms.mciweightconfig"
            ),
        ),
        migrations.CreateModel(
            name="MCICategoryLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("mci_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("mci_max", models.DecimalField(decimal_places=2, max_digits=5)),
                ("severity_order", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_intervention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mci_default_for",
                        to="grms.interventionlookup",
                    ),
                ),
            ],
            options={
                "ordering": ["severity_order", "mci_min"],
                "unique_together": {("code", "mci_min", "mci_max")},
            },
        ),
        migrations.AddField(
            model_name="segmentmciresult",
            name="mci_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="grms.mcicategorylookup",
            ),
        ),
        migrations.DeleteModel(
            name="ConditionRating",
        ),
    ]
