# Generated by Django 5.2.9 on 2025-12-11 06:53

from decimal import Decimal

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0035_alter_bridgeconditionsurvey_deck_condition_and_more"),
    ]

    def _seed_condition_factors(apps, schema_editor):
        ConditionFactorLookup = apps.get_model("grms", "ConditionFactorLookup")

        factor_rows = [
            # Drainage
            ("drainage", 1, Decimal("1.00"), "Good – No water on road during rain; good drainage"),
            ("drainage", 2, Decimal("2.00"), "Fair – Some water during rain; minor erosion"),
            ("drainage", 3, Decimal("3.00"), "Poor – Much water; severe erosion"),
            ("drainage", 4, Decimal("4.00"), "Bad – Non-functioning / non-existing drainage"),
            # Shoulder
            ("shoulder", 1, Decimal("1.00"), "Good – Good shape; water runs off road"),
            ("shoulder", 2, Decimal("2.00"), "Fair – Uneven shape; some runoff to drains"),
            ("shoulder", 3, Decimal("3.00"), "Poor – Poor shape; restricts water; erosion"),
            ("shoulder", 4, Decimal("4.00"), "Bad – Non-existing or non-functioning"),
            # Surface
            ("surface", 1, Decimal("1.00"), "Good – Smooth surface (<8 m/km)"),
            ("surface", 2, Decimal("2.00"), "Fair – Corrugations/potholes ≤ 10 cm (9–14 m/km)"),
            ("surface", 3, Decimal("3.00"), "Poor – Frequent depressions; rough (15–18 m/km)"),
            ("surface", 4, Decimal("4.00"), "Bad – Deep depressions/potholes; 4WD only (>18 m/km)"),
        ]

        for factor_type, rating, value, description in factor_rows:
            ConditionFactorLookup.objects.update_or_create(
                factor_type=factor_type,
                rating=rating,
                defaults={"factor_value": value, "description": description},
            )

    def _unseed_condition_factors(apps, schema_editor):
        ConditionFactorLookup = apps.get_model("grms", "ConditionFactorLookup")
        ConditionFactorLookup.objects.filter(
            factor_type__in=["drainage", "shoulder", "surface"], rating__in=[1, 2, 3, 4]
        ).delete()

    def _seed_mci_categories(apps, schema_editor):
        MCICategoryLookup = apps.get_model("grms", "MCICategoryLookup")

        categories = [
            ("Good Condition", "GOOD", Decimal("1.00"), Decimal("1.75"), 1),
            ("Fair Condition", "FAIR", Decimal("1.76"), Decimal("2.50"), 2),
            ("Poor Condition", "POOR", Decimal("2.51"), Decimal("3.25"), 3),
            ("Bad Condition", "BAD", Decimal("3.26"), Decimal("4.00"), 4),
        ]

        for name, code, mci_min, mci_max, order in categories:
            MCICategoryLookup.objects.update_or_create(
                code=code,
                mci_min=mci_min,
                mci_max=mci_max,
                defaults={
                    "name": name,
                    "severity_order": order,
                    "is_active": True,
                },
            )

    def _unseed_mci_categories(apps, schema_editor):
        MCICategoryLookup = apps.get_model("grms", "MCICategoryLookup")
        MCICategoryLookup.objects.filter(code__in=["GOOD", "FAIR", "POOR", "BAD"]).delete()

    operations = [
        migrations.RunPython(_seed_condition_factors, _unseed_condition_factors),
        migrations.RunPython(_seed_mci_categories, _unseed_mci_categories),
    ]
