# Generated by Django 5.2.8 on 2025-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0036_seed_mci_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionfactorlookup',
            name='factor_type',
            field=models.CharField(choices=[('drainage', 'Drainage Condition'), ('shoulder', 'Shoulder Condition'), ('surface', 'Surface Condition')], max_length=20),
        ),
    ]
