# Generated by Django 5.2.9 on 2025-12-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0037_alter_conditionfactorlookup_factor_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Intervention category",
                "verbose_name_plural": "Intervention categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InterventionWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_code", models.CharField(max_length=5, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=30)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_items",
                        to="grms.interventioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention work item",
                "verbose_name_plural": "Intervention work items",
                "ordering": ["work_code"],
            },
        ),
        migrations.AlterField(
            model_name="mcicategorylookup",
            name="default_intervention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mci_default_for",
                to="grms.interventionworkitem",
                to_field="work_code",
            ),
        ),
        migrations.AlterField(
            model_name="segmentmciresult",
            name="recommended_intervention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mci_results",
                to="grms.interventionworkitem",
                to_field="work_code",
            ),
        ),
    ]
