# Generated by Django 5.2.9 on 2025-12-11 11:51

from django.db import migrations


CATEGORIES = [
    "Maintenance",
    "Rehabilitation",
    "Bottleneck – Road",
    "Bottleneck – Structures",
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("grms", "InterventionCategory")
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)


def reverse_seed_categories(apps, schema_editor):
    Category = apps.get_model("grms", "InterventionCategory")
    Category.objects.filter(name__in=CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0038_interventioncategory_interventionworkitem_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=reverse_seed_categories),
    ]
