# Generated by Django 5.2.9 on 2025-12-11 11:51

from django.db import migrations


WORK_ITEMS = [
    ("01", "Routine Maintenance", "km/year", "Maintenance"),
    ("02", "Periodic Maintenance", "km", "Maintenance"),
    ("03", "Other (Reserved)", "km", "Maintenance"),
    ("04", "Spot Repair", "km", "Maintenance"),
    ("05", "Rehabilitation", "km", "Rehabilitation"),
    ("06", "Other (Reserved)", "km", "Rehabilitation"),
    ("101", "Embankment Filling", "km", "Bottleneck – Road"),
    ("102", "Other (Reserved)", "km", "Bottleneck – Road"),
    ("103", "Bridge New", "m", "Bottleneck – Structures"),
    ("104", "Bridge Repair Major", "m", "Bottleneck – Structures"),
    ("105", "Bridge Repair Minor", "m", "Bottleneck – Structures"),
    ("106", "Culvert New", "m", "Bottleneck – Structures"),
    ("107", "Culvert Repair Major", "m", "Bottleneck – Structures"),
    ("108", "Culvert Repair Minor", "m", "Bottleneck – Structures"),
    ("109", "Drift New", "m", "Bottleneck – Structures"),
    ("110", "Vented Drift New", "m", "Bottleneck – Structures"),
    ("111", "Other (Reserved)", "km", "Bottleneck – Structures"),
]


def seed_work_items(apps, schema_editor):
    Category = apps.get_model("grms", "InterventionCategory")
    WorkItem = apps.get_model("grms", "InterventionWorkItem")

    categories = {cat.name: cat for cat in Category.objects.all()}

    for code, description, unit, category_name in WORK_ITEMS:
        category = categories.get(category_name)
        if not category:
            continue
        WorkItem.objects.update_or_create(
            work_code=code,
            defaults={
                "category": category,
                "description": description,
                "unit": unit,
            },
        )


def reverse_work_items(apps, schema_editor):
    WorkItem = apps.get_model("grms", "InterventionWorkItem")
    WorkItem.objects.filter(work_code__in=[code for code, *_ in WORK_ITEMS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0039_seed_intervention_categories"),
    ]

    operations = [
        migrations.RunPython(seed_work_items, reverse_code=reverse_work_items),
    ]
