# Generated by Django 5.2.9 on 2025-12-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0040_seed_intervention_work_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentInterventionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mci_value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("calculated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_recommendations",
                        to="grms.interventionworkitem",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_recommendations",
                        to="grms.roadsegment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment intervention recommendation",
                "verbose_name_plural": "Segment intervention recommendations",
                "ordering": ["segment_id", "recommended_item__work_code"],
                "unique_together": {("segment", "recommended_item")},
            },
        ),
    ]
