# Generated by Django 5.2.9 on 2025-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0041_segmentinterventionrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCIRoadMaintenanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mci_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "mci_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("routine", models.BooleanField(default=False)),
                ("periodic", models.BooleanField(default=False)),
                ("rehabilitation", models.BooleanField(default=False)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "MCI road maintenance rule",
                "verbose_name_plural": "MCI road maintenance rules",
                "ordering": ["priority", "mci_min"],
            },
        ),
    ]
