# Generated by Django 5.2.9 on 2025-12-12 08:24

from decimal import Decimal

from django.db import migrations


def seed_rules(apps, schema_editor):
    Rule = apps.get_model("grms", "MCIRoadMaintenanceRule")

    defaults = [
        {
            "priority": 1,
            "mci_min": None,
            "mci_max": Decimal("1.50"),
            "routine": True,
            "periodic": False,
            "rehabilitation": False,
        },
        {
            "priority": 2,
            "mci_min": Decimal("1.50"),
            "mci_max": Decimal("2.50"),
            "routine": True,
            "periodic": True,
            "rehabilitation": False,
        },
        {
            "priority": 3,
            "mci_min": Decimal("2.50"),
            "mci_max": None,
            "routine": False,
            "periodic": False,
            "rehabilitation": True,
        },
    ]

    for data in defaults:
        Rule.objects.update_or_create(
            priority=data["priority"],
            defaults={**data, "is_active": True},
        )


def unseed_rules(apps, schema_editor):
    Rule = apps.get_model("grms", "MCIRoadMaintenanceRule")
    Rule.objects.filter(priority__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0042_mciroadmaintenancerule"),
    ]

    operations = [
        migrations.RunPython(seed_rules, unseed_rules),
    ]
