# Generated by ChatGPT

from decimal import Decimal

from django.db import migrations


def update_rules(apps, schema_editor):
    Rule = apps.get_model("grms", "MCIRoadMaintenanceRule")

    desired_rules = [
        {
            "priority": 1,
            "mci_min": None,
            "mci_max": Decimal("1.49"),
            "routine": True,
            "periodic": False,
            "rehabilitation": False,
        },
        {
            "priority": 2,
            "mci_min": Decimal("1.50"),
            "mci_max": Decimal("2.50"),
            "routine": True,
            "periodic": True,
            "rehabilitation": False,
        },
        {
            "priority": 3,
            "mci_min": Decimal("2.51"),
            "mci_max": None,
            "routine": False,
            "periodic": False,
            "rehabilitation": True,
        },
    ]

    for data in desired_rules:
        Rule.objects.update_or_create(
            priority=data["priority"], defaults={**data, "is_active": True}
        )


def noop_reverse(apps, schema_editor):
    """Keep existing rule configuration when reversing."""


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0043_seed_mci_road_rules"),
    ]

    operations = [
        migrations.RunPython(update_rules, noop_reverse),
    ]
