# Generated by Django 5.2.8 on 2025-12-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0049_update_roadsocioeconomic_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualWorkplanReport',
            fields=[
            ],
            options={
                'verbose_name': 'Annual Workplan (Table 26)',
                'verbose_name_plural': 'Annual Workplan (Table 26)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grms.road',),
        ),
        migrations.CreateModel(
            name='RoadGlobalCostReport',
            fields=[
            ],
            options={
                'verbose_name': 'Global Cost of Road Works',
                'verbose_name_plural': 'Global Cost of Road Works',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grms.road',),
        ),
        migrations.CreateModel(
            name='SectionWorkplanReport',
            fields=[
            ],
            options={
                'verbose_name': 'Section Annual Workplan (Table 25)',
                'verbose_name_plural': 'Section Annual Workplan (Table 25)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grms.road',),
        ),
        migrations.RenameField(
            model_name='segmentmciresult',
            old_name='mci_category',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='benefitfactor',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadrankingresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segmentinterventionneed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segmentinterventionneeditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='structureinterventionneed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='structureinterventionneeditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trafficforprioritization',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
