# Generated by Django 5.2.8 on 2025-12-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0050_annualworkplanreport_roadglobalcostreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcicategorylookup',
            old_name='code',
            new_name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='mcicategorylookup',
            unique_together={('rating', 'mci_min', 'mci_max')},
        ),
        migrations.RemoveField(
            model_name='mcicategorylookup',
            name='name',
        ),
    ]
