# Generated by Django 5.2.8 on 2025-11-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nightadjustmentlookup",
            new_name="night_adjus_hours_c_a13a7e_idx",
            old_name="night_adjus_hours_c_3d5d1a_idx",
        ),
        migrations.RenameIndex(
            model_name="pculookup",
            new_name="pcu_lookup_vehicle_506ac8_idx",
            old_name="pcu_lookup_vehicle_7e685b_idx",
        ),
        migrations.RenameIndex(
            model_name="trafficcountrecord",
            new_name="traffic_cou_traffic_709f2f_idx",
            old_name="traffic_coun_traffic_fccf74_idx",
        ),
        migrations.RenameIndex(
            model_name="trafficcountrecord",
            new_name="traffic_cou_road_se_c956ef_idx",
            old_name="traffic_coun_road_se_5c31ba_idx",
        ),
    ]
