# Generated by Django 5.2.8 on 2025-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "traffic",
            "0002_rename_night_adjus_hours_c_3d5d1a_idx_night_adjus_hours_c_a13a7e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficcountrecord",
            options={
                "verbose_name": "Traffic count",
                "verbose_name_plural": "Traffic counts",
            },
        ),
        migrations.RemoveIndex(
            model_name="trafficcountrecord",
            name="traffic_cou_traffic_709f2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="trafficcountrecord",
            name="traffic_cou_road_se_c956ef_idx",
        ),
        migrations.RemoveField(
            model_name="trafficcountrecord",
            name="count_value",
        ),
        migrations.RemoveField(
            model_name="trafficcountrecord",
            name="road_segment",
        ),
        migrations.RemoveField(
            model_name="trafficcountrecord",
            name="vehicle_class",
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="bicycles",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="buses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="cars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="heavy_goods",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="light_goods",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="medium_goods",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="minibuses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="motorcycles",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="pedestrians",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trafficcountrecord",
            name="tractors",
            field=models.IntegerField(default=0),
        ),
    ]
