# Generated by Django 5.2.8 on 2025-11-30 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grms", "0022_add_road_identifier"),
        ("traffic", "0002_add_missing_road_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficforprioritization",
            old_name="final_value",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="trafficsurvey",
            name="id",
        ),
        migrations.AlterUniqueTogether(
            name="trafficsurveysummary",
            unique_together={("road", "vehicle_class", "fiscal_year")},
        ),
        migrations.AddField(
            model_name="trafficsurvey",
            name="traffic_survey_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trafficsurvey",
            name="count_days_per_cycle",
            field=models.PositiveSmallIntegerField(
                default=7, help_text="Number of days counted in this cycle (must be 7)."
            ),
        ),
        migrations.AlterField(
            model_name="trafficsurvey",
            name="night_adjustment_factor",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.0"),
                help_text="Night adjustment factor used for this survey (derived).",
                max_digits=6,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trafficforprioritization",
            unique_together={("road", "fiscal_year", "is_active")},
        ),
        migrations.RemoveField(
            model_name="trafficsurveysummary",
            name="traffic_survey",
        ),
    ]
