# Generated by Django 5.2.8 on 2025-11-28 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from grms.gis_fields import PointField


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0021_alter_trafficsurvey_road_segment'),
        ('traffic', '0003_alter_trafficcountrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficforprioritization',
            old_name='value',
            new_name='final_value',
        ),
        migrations.RenameField(
            model_name='trafficsurveysummary',
            old_name='adt_class',
            new_name='adt_final',
        ),
        migrations.RenameField(
            model_name='trafficsurveysummary',
            old_name='pcu_class',
            new_name='pcu_final',
        ),
        migrations.AlterUniqueTogether(
            name='trafficcyclesummary',
            unique_together={('traffic_survey', 'road', 'vehicle_class', 'cycle_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trafficforprioritization',
            unique_together={('road', 'fiscal_year', 'value_type', 'is_active')},
        ),
        migrations.RemoveField(
            model_name='trafficqc',
            name='road_segment',
        ),
        migrations.AlterUniqueTogether(
            name='trafficsurvey',
            unique_together={('road', 'survey_year', 'cycle_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trafficsurveysummary',
            unique_together={('traffic_survey', 'road', 'vehicle_class')},
        ),
        migrations.AddField(
            model_name='trafficcyclesummary',
            name='road',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_cycle_summaries', to='grms.road'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficqc',
            name='qc_source',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='trafficqc',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_traffic_qc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trafficqc',
            name='road',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_qc_issues', to='grms.road'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficsurvey',
            name='road',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_surveys', to='grms.road'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficsurvey',
            name='station_location',
            field=PointField(default=None, help_text='GPS location of the counting station.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficsurveysummary',
            name='fiscal_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficsurveysummary',
            name='road',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_survey_summaries', to='grms.road'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trafficforprioritization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active record per road+fiscal_year+value_type.'),
        ),
        migrations.RemoveField(
            model_name='trafficcyclesummary',
            name='road_segment',
        ),
        migrations.RemoveField(
            model_name='trafficforprioritization',
            name='road_segment',
        ),
        migrations.RemoveField(
            model_name='trafficsurvey',
            name='location_override',
        ),
        migrations.RemoveField(
            model_name='trafficsurvey',
            name='road_segment',
        ),
        migrations.RemoveField(
            model_name='trafficsurveysummary',
            name='road_segment',
        ),
    ]
