# Generated by Django 5.2.8 on 2025-11-28 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from grms.gis_fields import PointField


def populate_road_fields(apps, schema_editor):
    Road = apps.get_model('grms', 'Road')
    TrafficSurvey = apps.get_model('traffic', 'TrafficSurvey')
    TrafficCycleSummary = apps.get_model('traffic', 'TrafficCycleSummary')
    TrafficSurveySummary = apps.get_model('traffic', 'TrafficSurveySummary')
    TrafficQc = apps.get_model('traffic', 'TrafficQc')
    TrafficForPrioritization = apps.get_model('traffic', 'TrafficForPrioritization')

    default_road = Road.objects.order_by('id').first()

    # Map surveys first so children can reuse survey.road
    for survey in TrafficSurvey.objects.all().select_related('road'):
        survey.road = survey.road or default_road
        survey.save(update_fields=['road'])

    # Cycle summaries
    for cycle in TrafficCycleSummary.objects.all().select_related('traffic_survey__road'):
        road = getattr(cycle.traffic_survey, 'road', None) or default_road
        cycle.road = road
        cycle.save(update_fields=['road'])

    # Survey summaries
    for summary in TrafficSurveySummary.objects.all().select_related('traffic_survey__road'):
        road = getattr(summary.traffic_survey, 'road', None) or default_road
        summary.road = road
        if summary.fiscal_year is None:
            summary.fiscal_year = getattr(summary.traffic_survey, 'survey_year', None) or 0
        summary.save(update_fields=['road', 'fiscal_year'])

    # QC issues
    for qc in TrafficQc.objects.all().select_related('traffic_survey__road'):
        road = getattr(qc.traffic_survey, 'road', None) or default_road
        qc.road = road
        qc.save(update_fields=['road'])

    # Prioritization snapshot (already had road, but ensure populated)
    for snap in TrafficForPrioritization.objects.all().select_related('road'):
        if snap.road_id:
            continue
        snap.road = default_road
        snap.save(update_fields=['road'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0021_alter_trafficsurvey_road_segment'),
        ('traffic', '0003_alter_trafficcountrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficforprioritization',
            old_name='value',
            new_name='final_value',
        ),
        migrations.RenameField(
            model_name='trafficsurveysummary',
            old_name='adt_class',
            new_name='adt_final',
        ),
        migrations.RenameField(
            model_name='trafficsurveysummary',
            old_name='pcu_class',
            new_name='pcu_final',
        ),
        migrations.AddField(
            model_name='trafficqc',
            name='qc_source',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='trafficqc',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_traffic_qc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trafficsurvey',
            name='station_location',
            field=PointField(help_text='GPS location of the counting station.', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='trafficsurveysummary',
            name='fiscal_year',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='trafficforprioritization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active record per road+fiscal_year+value_type.'),
        ),
        migrations.RunPython(populate_road_fields, noop),
        migrations.RemoveField(
            model_name='trafficsurvey',
            name='location_override',
        ),
        migrations.AlterField(
            model_name='trafficcyclesummary',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_cycle_summaries', to='grms.road'),
        ),
        migrations.AlterField(
            model_name='trafficqc',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_qc_issues', to='grms.road'),
        ),
        migrations.AlterField(
            model_name='trafficsurvey',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_surveys', to='grms.road'),
        ),
        migrations.AlterField(
            model_name='trafficsurveysummary',
            name='fiscal_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficsurveysummary',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_survey_summaries', to='grms.road'),
        ),
        migrations.AlterUniqueTogether(
            name='trafficcyclesummary',
            unique_together={('traffic_survey', 'road', 'vehicle_class', 'cycle_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trafficforprioritization',
            unique_together={('road', 'fiscal_year', 'value_type', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='trafficsurvey',
            unique_together={('road', 'survey_year', 'cycle_number')},
        ),
        migrations.AlterUniqueTogether(
            name='trafficsurveysummary',
            unique_together={('traffic_survey', 'road', 'vehicle_class')},
        ),
    ]
