# Generated by Django 5.2.8 on 2025-12-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic", "0004_road_level_traffic_overall"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trafficsurveyoverall",
            options={
                "verbose_name": "Traffic survey overall",
                "verbose_name_plural": "Road traffic summaries",
            },
        ),
    ]
