# Generated by Django 5.2.8 on 2025-11-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_rename_value_trafficforprioritization_final_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficqc',
            name='road_segment',
        ),
    ]
