# Generated by Django 5.2.8 on 2025-12-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_create_traffic_survey_overall_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsurveyoverall',
            options={'verbose_name_plural': 'Road traffic summaries'},
        ),
        migrations.AlterField(
            model_name='trafficsurveyoverall',
            name='overall_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
