# Generated by Django 5.2.8 on 2025-11-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_cleanup_legacy_columns'),
        ('traffic', '0005_remove_trafficqc_road_segment'),
    ]

    operations = [
    ]
