# Generated by Django 5.2.8 on 2025-12-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_alter_trafficsurveyoverall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficsurveyoverall',
            options={'verbose_name': 'Traffic survey overall', 'verbose_name_plural': 'Traffic surveys overall'},
        ),
    ]
