# Generated by Django 5.2.8 on 2025-11-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_safe_remove_legacy_state'),
        ('traffic', '0006_merge_20251128_1516'),
    ]

    operations = [
    ]
