# Generated by Django 5.2.8 on 2025-12-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grms', '0050_annualworkplanreport_roadglobalcostreport_and_more'),
        ('traffic', '0006_fix_summary_fk_column'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trafficsurveysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trafficforprioritization',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.SeparateDatabaseAndState(
    database_operations=[
        # traffic_survey_id already exists in DB, so we do NOT add the column again.
    ],
    state_operations=[
        migrations.AddField(
            model_name="trafficsurveysummary",
            name="traffic_survey",
            field=models.ForeignKey(
                to="traffic.trafficsurvey",   # confirm exact model label
                on_delete=models.CASCADE,     # match your model exactly
                related_name="summaries",     # match your model exactly
                null=True,
                blank=True,
            ),
        ),
    ],
),

        migrations.AlterField(
            model_name='trafficforprioritization',
            name='source_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_prioritization_values', to='traffic.trafficsurvey'),
        ),
        migrations.AlterField(
            model_name='trafficforprioritization',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trafficsurveysummary',
            unique_together={('traffic_survey', 'vehicle_class', 'fiscal_year', 'road')},
        ),
    ]
