MENU_GROUPS = {
    "Inventories": (
        "Roads",
        "Road socio-economic",
        "Road sections",
        "Road segments",
        "Structure inventories",
        "Furniture inventories",
        "Bridge details",
        "Culvert details",
        "Ford details",
        "Retaining wall details",
        "Gabion wall details",
    ),
    "Surveys – Condition": (
        "Road condition surveys",
        "Structure condition surveys",
        "Bridge condition surveys",
        "Culvert condition surveys",
        "Other structure condition surveys",
        "Furniture condition surveys",
    ),
    "Surveys – Severity & extent": (
        "Road condition detailed surveys",
        "Structure condition detailed surveys",
        "Furniture condition detailed surveys",
    ),
    "Traffic Data": (
        "TrafficSurvey",
        "TrafficSurveySummary",
        "TrafficSurveyOverall",
        "TrafficForPrioritization",
    ),
    "Traffic Data – Details": (
        "Traffic count records",
        "Traffic cycle summaries",
        "Traffic QCs",
    ),
    "Traffic Data – Lookups": (
        "PCU lookups",
        "Night adjustment lookups",
    ),
    "Maintenance & planning": (
        "Annual work plans",
        "Structure interventions",
        "Road section interventions",
        "Benefit factors",
        "Prioritization results",
    ),
    "Prioritization lookups": (
        "Road link type lookups",
        "Benefit categories",
        "Benefit criteria",
        "Benefit criterion scales",
    ),
    "Reference data": (
        "Condition ratings",
        "QA statuses",
        "Activity lookups",
        "Intervention lookups",
        "Unit costs",
        "Distress types",
        "Distress conditions",
        "Distress activities",
        "Admin zones",
        "Admin woredas",
    ),
}
